### ISSUE TITLE
Solving environment not completing

### ISSUE THREAD

**Issue by npschafer** [PacktPublishing/Causal-Inference-and-Discovery-in-Python#1]
The command `conda env create -f causal_book_py39_cuda117.yml` never finishes. Tested on Windows and WSL. Anyone else encountering this issue? Found a solution?

**Comment by araquejc** [comment]
> The command `conda env create -f causal_book_py39_cuda117.yml` never finishes. Tested on Windows and WSL. Anyone else encountering this issue? Found a solution?

Same here, tested in both.

**Comment by AlxndrMlk** [comment]
Thank you for the feedback @npschafer @araquejc, appreciate it!

A couple of questions to help me understand the problem:

* Which version of Windows do you use?
* Do you have a GPU, if so, did you install CUDA 11.7 drivers?
* Do you have Graphviz installed on your system?

Thank you for your patience, I must have missed this issue before. 

I'll make sure to turn the notifications on, not to miss your responses.

**Comment by AlxndrMlk** [comment]
Stale. Closing for now. 

Feel free to reopen if the issue persists or you have any new comments.
