### ISSUE TITLE
Small errata for p27 of book (post-June 2023)

### ISSUE THREAD

**Issue by j-at-ch** [PacktPublishing/Causal-Inference-and-Discovery-in-Python#10]
Loving that these resources are on GitHub - thank you @AlxndrMlk!

Quick notational suggestion: on p27, the line  $X_{sample} = 1.9 < X < -1.9$ doesn't make sense at the moment. 
The right-side reads as a boolean, and the condition can never be satisfied, as written.

Would be clearer what's meant if it was "...sampled according to the condition $X < - 1.9$ or $X > 1.9$".

**Comment by AlxndrMlk** [comment]
Hi @j-at-ch 

Thank you for pointing this out.

You're right, this is an abuse of notation and might be confusing.

I'll add this to the list of corrections for the next edition.

Best,
Alex

**Comment by j-at-ch** [comment]
Thanks @AlxndrMlk!
