### ISSUE TITLE
Chap 4 - `from_numpy_matrix` is deprecated

### ISSUE THREAD

**Issue by GawainGan** [PacktPublishing/Causal-Inference-and-Discovery-in-Python#12]
in networkx 3.0 the changelog shows the following "Remove to_numpy_matrix & from_numpy_matrix

Update the line of code: graph = nx.from_numpy_array(adj_matrix, create_using=nx.DiGraph)

**Comment by AlxndrMlk** [comment]
Hi @GawainGan 

That's correct.

The book's environment uses Networkx < 3.0 to achieve the compatibility with other packages in the environment.

We'll update the versions in the 2nd edition of the book and to my best knowledge we should be able to move to Networkx 3.+ as well.
