### ISSUE TITLE
Add bibtex reference to the book in the `README.md`

### ISSUE THREAD

**Issue by drbenvincent** [PacktPublishing/Causal-Inference-and-Discovery-in-Python#2]
It would be a real help for anyone wanting to cite the book if you could add the bibtex entry text to the bottom of the `README.md` 👍

Along the same lines... I'm not sure if it's under your control, but I also can't find the bibtex citation through a [Google Scholar search](https://scholar.google.co.uk/scholar?hl=en&as_sdt=0%2C5&q=Causal+Inference+and+Discovery+in+Python&btnG=).

**Comment by AlxndrMlk** [comment]
Hi @drbenvincent 

Thank you for the feedback, these are great points!

Added the citation section in the `README.md`, including *BibTeX* and *APA* formats.

Added the book to Google Scholar (not sure when it will be updated).

**Comment by AlxndrMlk** [comment]
@drbenvincent - I am closing the issue now.
