### ISSUE TITLE
Chapter 7 notebook array shape error messages

### ISSUE THREAD

**Issue by ksbystrom** [PacktPublishing/Causal-Inference-and-Discovery-in-Python#4]
Possibly related to the numba deprecation warning , the following code spits out an array shape error, which then propogates errors in the remaining cells in the chapter 7 notebook.  I tried upgrading shap to 0.42.0 which resolved some but not all of the errors. 

`estimate = model.estimate_effect(
    identified_estimand=estimand,
    method_name='backdoor.econml.dml.DML',
    method_params={
        'init_params': {
            'model_y': GradientBoostingRegressor(),
            'model_t': GradientBoostingRegressor(),
            'model_final': LassoCV(fit_intercept=False),
        },
        'fit_params': {}}
)

print(f'Estimate of causal effect (DML): {estimate.value}')
`

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

**Comment by ksbystrom** [comment]
I think this might be resolved in a later version of dowhy since I see they added the reshape functionality.  #https://github.com/py-why/dowhy/commit/b21d2ffe063d56066fbe63f15705bacff0eeb151

**Comment by AlxndrMlk** [comment]
Thank you for raising the issue @ksbystrom 

I'll look into it later this week.

**Comment by AlxndrMlk** [comment]
@ksbystrom - is this an error or a warning?

If the former, can you share the traceback?

Are you using the environment based on the `yml` file in the repo or a custom environment?

Thanks.

**Comment by ksbystrom** [comment]
I am using a custom environment, but confirmed that the error is also in this repo because you can see it in the published notebooks in the repo when they are generated directly in github.

**Comment by AlxndrMlk** [comment]
Hi @ksbystrom 

What you see in the notebooks is not an error, but a warning.

This means that the code executes properly.

These warnings result from differences in internal handling of shapes in DoWhy/EconML and their dependencies.

As you suggested it might be resolved in later versions of the library.

I'll start updating the code to later versions of the libraries as soon as I confirm that the later versions are stable and compatible with other packages in the environment.

Some later versions of some of the libraries used in the book introduced minor bugs that were leading to inconsistent results.

I'll make the updates after getting the confirmations from the developers that the packages are stable and after re-testing the code.

By that time, I recommend using the versions of the libraries used in provided environment files.

Hope that helps.
