### ISSUE TITLE
Notebook 13 np.np typo

### ISSUE THREAD

**Issue by ksbystrom** [PacktPublishing/Causal-Inference-and-Discovery-in-Python#5]
<img width="1040" alt="Screenshot 2023-12-26 at 11 21 30 PM" src="https://github.com/PacktPublishing/Causal-Inference-and-Discovery-in-Python/assets/16736841/bbc45e62-a23d-47f9-8ebc-9e6436ae49a6">

Notebook 13 seems to have a typo of np.np.tril, which causes an error. Changing to np.tril resolves this error.

**Comment by AlxndrMlk** [comment]
Thank you @ksbystrom for spotting this! 

I just pushed an update.
