### ISSUE TITLE
[Chapter9] Causal_estimator.effect for prediction

### ISSUE THREAD

**Issue by JakeLeeKorea** [PacktPublishing/Causal-Inference-and-Discovery-in-Python#7]
Hello, I am Jake Lee from Korea, a passionate reader of your book

I have found that couple of codes not working for prediction part in Ch09.
Your code flow as following
1. Instantiate Causal model
2. Estimand 
3. Estimate
4. Predict test data using .causal_estimator.effect

However #4 is not working from my side (description said there is no object of causal_estimator)
It would be appreciate if you give me help on it, especially in case that code is running in latest DoWhy version (11.0)

Thanks in advance!
Jake

**Comment by AlxndrMlk** [comment]
Hi @JakeLeeKorea 

The code might not be compatible with newer versions of packages.

Please see my reply in https://github.com/PacktPublishing/Causal-Inference-and-Discovery-in-Python/issues/4 for the details.

**Comment by AlxndrMlk** [comment]
Hi @JakeLeeKorea 

Thank you for your patience.

`dowhy` 0.11 lost back compatibility with 0.8.

Adding `dowhy` 0.11 to the book environment would cause a long chain reaction of incompatibilities with other libraries.

I know that `dowhy` 0.11.1 fixes some of these problems with back compatibility, but perhaps not all of them.

We'll be updating libraries to newer versions in the 2nd edition of the book. 

For the time being, I recommend using the environment provided in the repo for a smooth experience with the book and code examples.

Hope that helps.
